-- ### Icons

-- DESCRIPTION:
--
-- If you can't see the default icons:
-- Install nerd fonts and set it as your term font: https://www.nerdfonts.com/

--    Sections:
--      -> which-key
--      -> heirline-components (tabline)
--      -> heirline-components (winbar)
--      -> heirline-components (statuscolumn)
--      -> heirline-components (statusline)
--      -> heirline-components (misc)
--      -> Neotree
--      -> Git
--      -> DAP
--      -> Telescope
--      -> Nvim-lightbulb
--      -> Mason
--      -> Render-markdown

return {
  -- Which-key
  Debugger = "",
  Run = "󰑮",
  Find = "",
  Session = "󱂬",
  Sort = "󰒺",
  Buffer = "󰓩",
  Terminal = "",
  UI = "",
  Test = "󰙨",
  Packages = "󰏖",
  Docs = "",
  Git = "󰊢",
  LSP = "",

  -- Heirline-components - tabline
  BufferClose = "󰅖",
  FileModified = "",
  FileReadOnly = "",
  ArrowLeft = "",
  ArrowRight = "",
  TabClose = "󰅙",

  -- Heirline-components - winbar
  CompilerPlay = "",
  CompilerStop = "",
  CompilerRedo = "",
  NeoTree = "",
  Aerial = "",
  ZenMode = "󰰶",
  BufWrite = "",
  BufWriteAll = "",
  Ellipsis = "…",
  BreadcrumbSeparator = "",

  -- Heirline-components - statuscolumn
  FoldClosed = "",
  FoldOpened = "",
  FoldSeparator = " ",

  -- Heirline-components - statusline
  ActiveLSP = "",
  ActiveTS = "",
  Environment = "",
  DiagnosticError = "",
  DiagnosticHint = "󰌵",
  DiagnosticInfo = "󰋼",
  DiagnosticWarn = "",
  LSPLoading1 = "",
  LSPLoading2 = "󰀚",
  LSPLoading3 = "",
  SearchCount = "",
  MacroRecording = "",
  ToggleResults = "󰑮",

  -- Heirline-components - misc
  Paste = "󰅌",
  PathSeparator = "",

  -- Neotree
  FolderClosed = "",
  FolderEmpty = "",
  FolderOpen = "",
  Diagnostic = "󰒡",
  DefaultFile = "󰈙",

  -- Git
  GitBranch = " ",
  GitAdd = " ",
  GitChange = " ",
  GitDelete = " ",
  GitConflict = " ",
  GitIgnored = "◌ ",
  GitRenamed = "➜ ",
  GitSign = "▎",
  GitStaged = "✓ ",
  GitUnstaged = "✗ ",
  GitUntracked = "★ ",

  -- DAP
  DapBreakpoint = "",
  DapBreakpointCondition = "",
  DapBreakpointRejected = "",
  DapLogPoint = ".>",
  DapStopped = "󰁕",

  -- Telescope
  PromptPrefix = "❯",

  -- Nvim-lightbulb
  Lightbulb = "💡",

  -- Alpha
  GreeterNew = "📄",
  GreeterRecent = "🌺",
  GreeterYazi = "🦆",
  GreeterSessions = "🔎",
  GreeterProjects = "💼",
  GreeterPlug = "",

  -- Mason
  MasonInstalled = "✓",
  MasonUninstalled = "✗",
  MasonPending = "⟳",
  -- Render-markdown
  RenderMarkdown = { ' ', ' ', '󰲥 ', '󰲧 ', '󰲩 ', '󰲫 ' },
  ["diagnostics"] = {
    global = ' ',
    hint = '󰌵 ',
    other = ' ',
    error = ' ',
    info = ' ',
    question = ' ',
    warn = ' ',
  },
  ["documents"] = {
    -- Documents
    File = ' ',
    FileEmpty = ' ',
    Files = ' ',
    Folder = ' ',
    FolderEmpty = ' ',
    OpenFolder = ' ',
    OpenFolderEmpty = ' ',
    SymLink = ' ',
    SymlinkFolder = ' ',
    Import = ' ',
  },
  ["git"] = {
    Add = ' ',
    AddAlt = ' ',
    Branch = ' ',
    Diff = ' ',
    DiffAlt = ' ',
    Ignore = '◌ ',
    Mod = ' ',
    Octoface = ' ',
    Remove = ' ',
    RemoveAlt = ' ',
    Rename = ' ',
    Repo = ' ',
    Tag = ' ',
    Untrack = ' ',
  },
  ["kind"] = {
    Class = ' ',
    Color = ' ',
    Constant = ' ',
    Constructor = '󰈏 ',
    Enum = ' ',
    EnumMember = ' ',
    Event = ' ',
    Field = ' ',
    File = ' ',
    Folder = ' ',
    Function = '󰊕 ',
    Interface = ' ',
    Keyword = ' ',
    Method = ' ',
    Module = '',
    Operator = ' ',
    Property = ' ',
    Reference = ' ',
    Snippet = ' ',
    Struct = ' ',
    Text = ' ',
    TypeParameter = ' ',
    Unit = ' ',
    Value = ' ',
    Variable = ' ',
  },
  ["type"] = {
    Array = ' ',
    Boolean = '⏻ ',
    Number = ' ',
    Object = ' ',
    String = ' ',
  },
  ["ui"] = {
    Arrow = ' ',
    ArrowClosed = ' ',
    ArrowLeft = ' ',
    ArrowOpen = ' ',
    ArrowRight = ' ',
    Bluetooth = ' ',
    Bookmark = '',
    Bug = ' ',
    Calendar = ' ',
    Camera = ' ',
    Check = ' ',
    ChevronRight = '',
    Circle = ' ',
    CircleSmall = '● ',
    CircleSmallEmpty = '○ ',
    Clipboard = ' ',
    Close = ' ',
    Code = ' ',
    Collection = ' ',
    Color = ' ',
    Command = ' ',
    Comment = ' ',
    Copilot = ' ',
    CopilotError = ' ',
    Corner = '└ ',
    Dashboard = ' ',
    Database = ' ',
    Download = ' ',
    Edge = '│ ',
    Electric = ' ',
    Eye = ' ',
    Fire = ' ',
    Firefox = ' ',
    Flag = ' ',
    Game = ' ',
    Gear = ' ',
    GitHub = ' ',
    Heart = ' ',
    History = ' ',
    Home = ' ',
    Incoming = ' ',
    Jump = ' ',
    Keyboard = '  ',
    Ligthbulb = '󰌵 ',
    List = '',
    Lock = ' ',
    Minus = '‒ ',
    Music = '󰝚 ',
    Neovim = ' ',
    NewFile = ' ',
    None = ' ',
    Note = ' ',
    Outgoing = ' ',
    Package = ' ',
    Paint = ' ',
    Pause = ' ',
    Pencil = ' ',
    Person = ' ',
    Pin = '',
    Play = '',
    Plug = '',
    Plus = '',
    Power = ' ',
    PowerlineArrowLeft = '',
    PowerlineArrowRight = '',
    PowerlineLeftRound = '',
    PowerlineRightRound = '',
    Project = ' ',
    Question = ' ',
    Reload = ' ',
    Rocket = ' ',
    Save = '󰆓 ',
    Search = ' ',
    Separator = '▊ ',
    SeparatorLight = '▍',
    SeparatorDashed = '┆',
    SignIn = ' ',
    SignOut = ' ',
    Sleep = '󰒲 ',
    Star = ' ',
    Table = ' ',
    Telescope = ' ',
    Terminal = ' ',
    Test = ' ',
    Time = ' ',
    Topline = '‾',
    Trash = ' ',
    User = ' ',
    Vim = ' ',
    Wifi = ' ',
    Windows = ' ',
  },
  ["common"] = {
    unix = '',
    dos = '',
    mac = '',
    vim = '',
    vline = '▌',
    terminal = '',
    plugins = '',
    time = '󱑍',
    project = '',
    explorer = '',
    folder = '󰉋',
    folder_close = '󰉋',
    folder_open = '󰝰',
    folder_empty = '󰉖',
    file = '󰈙',
    search_in_files = '󱔗',
    search = '',
    help = '󰞋',
    quit = '󰅗',
    buffer = '󱔗',
    git = '',
    lsp = '',
    separator = '➤',
    dot = '',
    fix = '',
    todo = '',
    hack = '',
    warning = '',
    performance = '󰔠',
    note = '󰠮',
    test = '',
    trace = '',
    down = '',
    up = '',
    save = '',
    lock = '',
    light_bulb = '',
  },
  ["git_status"] = {
    added = '',
    deleted = '',
    modified = '',
    renamed = '',
    untracked = '',
    ignored = '',
    unstaged = '󰄗',
    staged = '󰄵',
    conflict = '',
  },
  ["ctrlspace"] = {
    CS = '',
    Sin = '',
    All = '',
    Vis = '',
    File = '󰈙',
    Tabs = '󰄮',
    CTab = '󰡖',
    NTM = '',
    WLoad = '󰜮',
    WSave = '󰜷',
    Zoom = '',
    SLeft = '',
    SRight = '',
    BM = '',
    Help = '',
    IV = '󰄗',
    IA = '󰄵',
    IM = ' ',
    Dots = '',
  },
  ["cmp"] = {
    Folder = ' 󰝰 (Folder)',
    File = ' 󰈙 (File)',
    Namespace = '  (Namespace)',
    Package = '  (Package)',
    Module = '  (Module)',
    Interface = '  (Interface)',
    Constructor = '   (Constructor)',
    Enum = ' 󰕘 (Enum)',
    EnumMember = ' 󰕚 (EnumMember)',
    Class = ' 󰊾 (Class)',
    Method = ' 󰡱 (Method)',
    Function = ' 󰊕 (Function)',
    Property = '  (Property)',
    Field = ' 󰢤 (Field)',
    Constant = ' 󰐃 (Constant)',
    Variable = ' 󰯍 (Variable)',
    String = ' 󰬶 (String)',
    Number = ' 󰎠 (Number)',
    Boolean = ' ◩ (Boolean)',
    Array = '  (Array)',
    Lines = '  (Lines)',
    Object = ' 󰅩 (Object)',
    Key = ' 󰌈 (Key)',
    Null = ' 󰟢 (Null)',
    Struct = '  (Struct)',
    Event = '  (Event)',
    Operator = ' 󱓉 (Operator)',
    TypeParameter = '󰊄 (TypeParameter)',
    Text = ' 󰬶 (Text) ',
    Words = ' 󰬶 (Words) ',
    Unit = '  (Unit)',
    Value = ' 󱗽 (Value)',
    Keyword = ' 󰌈 (Keyword)',
    Snippet = '  (Snippet)',
    Color = ' 󰌁 (Color)',
    Reference = ' 󰡌 (Reference)',
    Chars = ' 󰡌 (Chars)',
  },
  -- 󰕐 󰘯 󰖷   󰁁 󰃐 󰮄 󱗽 󰡱 󰋙󰌋 󰷖 󰧾 󰨑 󰒟 󱦜 󱄽 󰕘 󰕚    󰡌 󰢤 󰊾 󰯍 󰨝 󱒊 󰬶 󰎠 󱎆
  ["lsp"] = {
    File = '󰈙 ',
    Module = ' ',
    Namespace = ' ',
    Package = ' ',
    Class = '󰊾 ',
    Method = '󰡱 ',
    Property = ' ',
    Field = '󰢤 ',
    Constructor = '  ',
    Enum = '󰕘 ',
    EnumMember = '󰕚 ',
    Interface = ' ',
    Function = '󰊕 ',
    Variable = '󰯍 ',
    Constant = '󰐃 ',
    String = '󰬶 ',
    Number = '󰎠 ',
    Boolean = '◩ ',
    Array = ' ',
    Object = '󰅩 ',
    Key = '󰌈 ',
    Null = '󰟢 ',
    Struct = ' ',
    Event = ' ',
    Operator = '󱓉 ',
    TypeParameter = '󰊄 ',
  },
  ["outline"] = {
    File = { icon = '󰈙', hl = '@directory' },
    Module = { icon = '', hl = '@include' },
    Namespace = { icon = '', hl = '@namespace' },
    Package = { icon = '', hl = '@include' },
    Class = { icon = '󰊾', hl = '@structure' },
    Method = { icon = '󰡱', hl = '@method' },
    Property = { icon = '', hl = '@property' },
    Field = { icon = '󰢤', hl = '@field' },
    Constructor = { icon = '', hl = '@constructor' },
    Enum = { icon = '󰕘', hl = '@field' },
    Interface = { icon = '', hl = '@type' },
    Function = { icon = '󰊕', hl = '@function' },
    Variable = { icon = '󰯍', hl = '@variable' },
    Constant = { icon = '󰐃', hl = '@constant' },
    String = { icon = '󰬶', hl = '@string' },
    Number = { icon = '󰎠', hl = '@number' },
    Boolean = { icon = '◩', hl = '@boolean' },
    Array = { icon = '', hl = '@field' },
    Object = { icon = '󰅩', hl = '@type' },
    Key = { icon = '󰌈', hl = '@keyword' },
    Null = { icon = '󰟢', hl = '@comment' },
    EnumMember = { icon = '󰕚', hl = '@field' },
    Struct = { icon = '', hl = '@structure' },
    Event = { icon = '', hl = '@keyword' },
    Operator = { icon = '󱓉', hl = '@operator' },
    TypeParameter = { icon = '󰊄', hl = '@type' },
    Component = { icon = '󰅴', hl = 'Function' },
    Fragment = { icon = '󰅴', hl = 'Constant' },
    -- ccls
    TypeAlias = { icon = ' ', hl = 'Type' },
    Parameter = { icon = ' ', hl = 'Identifier' },
    StaticMethod = { icon = ' ', hl = 'Function' },
    Macro = { icon = ' ', hl = 'Function' },
  },
  ["navbuddy"] = {
    File = '󰈙 ',
    Namespace = ' ',
    Package = ' ',
    Module = ' ',
    Interface = ' ',
    Constructor = ' ',
    Enum = '󰕘 ',
    EnumMember = '󰕚 ',
    Class = '󰊾 ',
    Method = '󰡱 ',
    Function = '󰊕 ',
    Property = ' ',
    Field = '󰢤 ',
    Constant = '󰐃 ',
    Variable = '󰯍 ',
    String = '󰬶 ',
    Number = '󰎠 ',
    Boolean = '◩ ',
    Array = ' ',
    Object = '󰅩 ',
    Key = '󰌈 ',
    Null = '󰟢 ',
    Struct = ' ',
    Event = ' ',
    Operator = '󱓉 ',
    TypeParameter = '󰊄 ',
  },
  ["lazy"] = {
    cmd = ' ',
    config = '',
    event = '',
    ft = ' ',
    init = ' ',
    import = ' ',
    keys = ' ',
    lazy = '󰒲 ',
    loaded = '●',
    not_loaded = '○',
    plugin = ' ',
    runtime = ' ',
    ' ',
    start = '',
    task = '󰸞 ',
    list = {
      '●',
      '➜',
      '',
      '‒',
    },
  },
  ["mason"] = {
    package_installed = ' ',
    package_pending = '󰆴 ',
    package_uninstalled = ' ',
  },
  ["dap_ui"] = {
    base = { expanded = '', collapsed = '', current_frame = '' },
    controls = {
      pause = '',
      play = '',
      step_into = '',
      step_over = '',
      step_out = '',
      step_back = '',
      run_last = '',
      terminate = '',
      disconnect = '',
    },
    sign = {
      breakpoint = '',
      reject = '',
      condition = '',
      stopped = '󰏤',
      log_point = '',
    },
  },
}
